image: java:8-jdk

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew check
    
after_script:
  - echo "End CI"
